# LISTAR USUÁRIOS - CORRETO
GET http://localhost/back-end-02/atividade/api/users/list.php HTTP/1.1
### 

# LISTAR USUÁRIOS - METHOD NOT ALLOWED
POST http://localhost/back-end-02/atividade/api/users/list.php HTTP/1.1
### 

# OBTER USUÁRIO - CORRETO
GET http://localhost/back-end-02/atividade/api/users/get.php?id=1 HTTP/1.1
###

# OBTER USUÁRIO - BAD REQUEST (ID INVÁLIDO)
GET http://localhost/back-end-02/atividade/api/users/get.php?id=aaa HTTP/1.1
###

# OBTER USUÁRIO - NOT FOUND
GET http://localhost/back-end-02/atividade/api/users/get.php?id=999 HTTP/1.1
###

# ADICIONAR USUÁRIO - CORRETO NA PRIMEIRA VEZ, CONFLICT NA SEGUNDA
POST http://localhost/back-end-02/atividade/api/users/add.php HTTP/1.1
Content-Type: application/json

{
    "name": "Haroldo",
    "email": "haroldo@email.com",
    "password": "haroldo",
    "is_admin": 0
}
###

# ADICIONAR USUÁRIO - CORPO INVÁLIDO (FALTANDO CAMPOS)
POST http://localhost/back-end-02/atividade/api/users/add.php HTTP/1.1
Content-Type: application/json

{
    "email": "haroldo@email.com",
    "password": "haroldo",
    "is_admin": 0
}
###

# ADICIONAR USUÁRIO - CORPO INVÁLIDO (FORMATO ERRADO)
POST http://localhost/back-end-02/atividade/api/users/add.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=Haroldo&email=haroldo%40email.com&password=haroldo&is_admin=0
###

# ATUALIZAR USUÁRIO - CORRETO
PUT http://localhost/back-end-02/atividade/api/users/update.php?id=3 HTTP/1.1
Content-Type: application/json

{
    "name": "Carlota Alterada",
    "email": "carlota@email.com",
    "is_admin": 1
}
###

# ATUALIZAR USUÁRIO - BAD REQUEST (FALTANDO CAMPOS)
PUT http://localhost/back-end-02/atividade/api/users/update.php?id=3 HTTP/1.1
Content-Type: application/json

{
    "email": "carlota@email.com",
    "is_admin": 1
}
###

# ATUALIZAR USUÁRIO - CONFLICT (EMAIL JÁ EXISTE)
PUT http://localhost/back-end-02/atividade/api/users/update.php?id=3 HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name": "Carlota Alterada",
    "email": "alvirinha@email.com",
    "is_admin": 1
}
###

# ATUALIZAR USUÁRIO - NOT FOUND 
PUT http://localhost/back-end-02/atividade/api/users/update.php?id=999 HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "name": "Carlota Alterada",
    "email": "alvirinha@email.com",
    "is_admin": 1
}
###

# DELETAR USUÁRIO - CORRETO DA PRIMEIRA VEZ, NOT FOUND NA SEGUNDA
DELETE http://localhost/back-end-02/atividade/api/users/delete.php?id=8 HTTP/1.1
###

# DELETAR USUÁRIO - BAD REQUEST (ID INVÁLIDO)
DELETE http://localhost/back-end-02/atividade/api/users/delete.php?id=aaa HTTP/1.1
###

# SET ADMIN - CORRETO
PATCH http://localhost/back-end-02/atividade/api/users/set_admin.php?id=3 HTTP/1.1
Content-Type: application/json

{
    "is_admin": 1
}
###

# SET ADMIN - BAD REQUEST (CAMPO INVÁLIDO)
PATCH http://localhost/back-end-02/atividade/api/users/set_admin.php?id=3 HTTP/1.1
Content-Type: application/json

{
    "is_admin": 2
}
###

# SET ADMIN - NOT FOUND(USUÁRIO INVÁLIDO)
PATCH http://localhost/back-end-02/atividade/api/users/set_admin.php?id=44 HTTP/1.1
Content-Type: application/json

{
    "is_admin": 1
}
